GET http://localhost:3000/api/eventos


###
GET http://localhost:3000/api/corredores

###
POST http://localhost:3000/api/corredores/registro
Content-Type: application/json

{
    "nombre": "Marco",
    "apellidos": "Leoncio",
    "edad": 32,
    "email": "marco@gmail.com",
    "password": "123456",
    "telefono": 123456789,
    "nivel": "principiante",
    "zona": "Madrid Capital"
}

###
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
"imagen": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Runner_Runner.jpg/250px-Runner_Runner.jpg",
"titulo": "Carrera diurna",
"nivel": "Avanzado",
"fecha": "2020-12-23",
"hora": "23:00",
"zona": "Madrid Norte"
}

###
POST http://localhost:3000/api/comentarios
Content-Type: application/json

{
    "titulo": "Hola",
    "comentario": "Hola amigüitos!"
}

###
GET http://localhost:3000/api/comentarios

###
DELETE http://localhost:3000/api/comentarios/8
Content-Type: application/json

###
GET http://localhost:3000/api/corredores/2

###
POST http://localhost:3000/api/corredores/registro
Content-Type: application/json

{
    "nombre": "Leo",
    "apellidos": "Messi",
    "edad": 35,
    "email": "leo@mail.com",
    "password": 12345,
    "telefono": 931234567,
    "nivel": "avanzado",
    "zona": "Madrid Capital"
}
