GET http://localhost:3000/api/eventos


###
GET http://localhost:3000/api/corredores
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjE2LCJjYWR1Y2lkYWQiOjE2MDg1Njc1ODIsImlhdCI6MTYwODU2MDM4Mn0.iDZf0qaAD1hTodWQUG8bzCFrujIfHSUWrp7D5MCrwQY

###
POST http://localhost:3000/api/corredores/registro
Content-Type: application/json

{
    "nombre": "Sofia",
    "apellidos": "Martin",
    "edad": 27,
    "email": "sofia@mail.com",
    "password": "12345",
    "telefono": 123456780,
    "nivel": "Avanzado",
    "zona": "Madrid Capital"
}

###
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
"imagen": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Runner_Runner.jpg/250px-Runner_Runner.jpg",
"titulo": "Carrera diurna",
"nivel": "Avanzado",
"fecha": "2020-12-23",
"hora": "23:00",
"zona": "Madrid Norte"
}

###
POST http://localhost:3000/api/comentarios
Content-Type: application/json

{
    "titulo": "Hola",
    "comentario": "Hola amigüitos!"
}

###
GET http://localhost:3000/api/comentarios

###
DELETE http://localhost:3000/api/comentarios/11
Content-Type: application/json

###
DELETE http://localhost:3000/api/eventos/24
Content-Type: application/json


###
GET http://localhost:3000/api/eventos/10

###
POST http://localhost:3000/api/corredores/login
Content-Type: application/json

{
    "email": "lol@mail.com",
    "password": "12345"
}

###
GET http://localhost:3000/api/corredores/perfil
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjE3LCJjYWR1Y2lkYWQiOjE2MDg2MzI3MDUsImlhdCI6MTYwODYyNTUwNX0.ZXC0wSdz9neOjIBpPKd5GE4W0QVeK1aR4poCMsgWrvw

###
GET http://localhost:3000/api/eventos/nivel/avanzado

###
GET http://localhost:3000/api/eventos/zona/madrid sur

###
POST http://localhost:3000/api/eventos/joined
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjE3LCJjYWR1Y2lkYWQiOjE2MDg1NDYyNDYsImlhdCI6MTYwODUzOTA0Nn0.fYZVXlgq19h9JLA_DwnIzdrAdrHf7BL4Jc2ynUIfF-c

{
    "eventoId": 25
}

###
POST http://localhost:3000/api/publicados
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjE3LCJjYWR1Y2lkYWQiOjE2MDg2MzI3MDUsImlhdCI6MTYwODYyNTUwNX0.ZXC0wSdz9neOjIBpPKd5GE4W0QVeK1aR4poCMsgWrvw

{
    "titulo": "Hola!!",
    "comentario": "Llevo corriendo maratones 5 años"
}

###
GET http://localhost:3000/api/publicados/17
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjE3LCJjYWR1Y2lkYWQiOjE2MDg2MzI3MDUsImlhdCI6MTYwODYyNTUwNX0.ZXC0wSdz9neOjIBpPKd5GE4W0QVeK1aR4poCMsgWrvw

###
DELETE http://localhost:3000/api/publicados/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjE3LCJjYWR1Y2lkYWQiOjE2MDg2MzI3MDUsImlhdCI6MTYwODYyNTUwNX0.ZXC0wSdz9neOjIBpPKd5GE4W0QVeK1aR4poCMsgWrvw