GET http://localhost:3000/api/eventos

###
GET http://localhost:3000/api/usuarios

###
POST http://localhost:3000/api/usuarios/registro

###
GET http://localhost:3000/api/corredores

###
POST http://localhost:3000/api/eventos
Content-Type: application/json

{
"imagen": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Runner_Runner.jpg/250px-Runner_Runner.jpg",
"titulo": "Carrera diurna",
"nivel": "Avanzado",
"fecha": "2020-12-23",
"hora": "23:00",
"zona": "Madrid Norte"
}

###
POST http://localhost:3000/api/comentarios
Content-Type: application/json

{
    "titulo": "Hola",
    "comentario": "Hola corredores!"
}

###
GET http://localhost:3000/api/comentarios

###
DELETE http://localhost:3000/api/comentarios/5
Content-Type: application/json